version: '3'

networks:
  upwork-network:
    name: upwork-network

services:
  ext-api:
    image: ext-api-image
    container_name: ext-api
    networks:
      - upwork-network
    ports:
      - "8000:8000"


  producer:
    image: producer-image
    container_name: php-app-producer
    networks:
      - upwork-network
    ports:
      - "90:80"
    depends_on:
      - ext-api